import Head from "next/head"
import Image from "next/image"
import { useEffect, useState, useCallback } from "react"
import { Images } from "../../utils/images"
import { Text } from "../../components/text"
import { Navbar } from "../../components/navabr"
import { Footer } from "../../components/footer"
import { WorkCard } from "../../components/card/work"
import { EducationCard } from "../../components/card/education"
import { SocialCard } from "../../components/card/social"
import { BookOpen, Flag, MapPin, User } from "react-feather"
import { DataTable } from "../../components/table"
import { NoContent } from "../../components/no-content"
import { ResearcherShowPreloader } from "../../components/preloader"
import { dateTodate } from "../../utils/helper"
import { ResearcherPublicProfile, ResearcherPublications } from "../../pages/api"

const index = ({ userName, user }) => {
    const [show, setShow] = useState(false)
    const [isLoading, setLoading] = useState(true)

    const [perPage, setPerPage] = useState(10)
    const [totalRows, setTotalRows] = useState(0)
    const [publications, setPublications] = useState([])
    const [publicationLoading, setPublicationLoading] = useState(true)

    /* fetch publication */
    const fetchPublications = useCallback(async (userName, page) => {
        try {
            setPublicationLoading(true)
            const response = await ResearcherPublications(userName, page, perPage)
            if (response.status === 200) {
                console.log(response.data.data);
                setPublications(response.data.data)
                setTotalRows(response.data.pagination ? response.data.pagination.total_items : 10)
            }
            setPublicationLoading(false)
        } catch (error) {
            if (error) {
                console.log(error.response)
                setPublicationLoading(false)
            }
        }
    }, [userName, perPage])

    useEffect(() => {
        setTimeout(() => {
            setLoading(false)
        }, 1000)
    }, [user])

    useEffect(() => {
        if (userName && user) fetchPublications(userName, 1)
    }, [userName, fetchPublications])

    // handle paginate page change
    const handlePageChange = page => fetchPublications(userName, page)

    // handle paginate row change
    const handlePerRowsChange = async (newPerPage, page) => {
        setPublicationLoading(true)
        const response = await ResearcherPublications(userName, page, newPerPage)
        setPublicationLoading(false)
        setPublications(response.data.data)
        setPerPage(newPerPage)
    }

    // data columns
    const columns = [
        {
            name: "Published date",
            sortable: true,
            selector: row => row.publicationDate ? dateTodate(row.publicationDate) : "N/A"
        },
        {
            name: "Category",
            sortable: true,
            selector: row => row?.category?.title
        },
        {
            name: "Title",
            sortable: true,
            selector: row => row.title
        },
        {
            name: "Details",
            width: "120px",
            cell: row =>
                <button
                    type="button"
                    className="w-full text-xs rounded-md transition-all py-2 text-gray-400 bg-gray-100 hover:text-black hover:bg-gray-200"
                    onClick={() => console.log(row)}
                >Show details</button>
        }
    ]


    return (
        <div>
            <Head>
                <title>ResearchTop || researcher profiles</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar user={""} />

            <div className="container mx-auto mt-[74px] py-[30px]">

                {isLoading ? <ResearcherShowPreloader /> : null}
                {!isLoading && !user ? <NoContent message="Account not available." /> : null}

                <div className="grid grid-cols-1">
                    <div className="lg:flex">

                        {/* Profile information */}
                        {!isLoading && user ?
                            <div className="w-full lg:max-w-[350px] mb-10 lg:mb-0 lg:pr-5 overflow-x-hidden">
                                <div className="text-center lg:text-left mb-4">
                                    <Image
                                        src={Images.Avatar}
                                        alt="avatar"
                                        width={120}
                                        height={120}
                                    />

                                    <Text className="text-md font-medium capitalize">{user.name}</Text>
                                </div>

                                <div>

                                    {/* About */}
                                    <Text className="text-sm font-normal leading-relaxed text-gray-500 mb-3">{user.about}</Text>

                                    {/* Address */}
                                    <table className="table-auto mb-4">
                                        <tbody>

                                            {user?.address ?
                                                <tr>
                                                    <td className="w-[25px]">
                                                        <MapPin size={16} />
                                                    </td>
                                                    <td>
                                                        <Text className="text-sm font-normal text-gray-500">{user.address}</Text>
                                                    </td>
                                                </tr>
                                                : null
                                            }

                                            {user?.country ?
                                                <tr>
                                                    <td className="w-[25px]">
                                                        <Flag size={16} />
                                                    </td>
                                                    <td>
                                                        <Text className="text-sm font-normal !break-all text-gray-500">{user.country}</Text>
                                                    </td>
                                                </tr>
                                                : null
                                            }

                                            <tr>
                                                <td className="w-[25px]">
                                                    <BookOpen size={16} />
                                                </td>
                                                <td>
                                                    <Text className="text-sm font-normal !break-all text-gray-500">
                                                        {user?.publications ? user.publications + " publications" : "Publication not available."}
                                                    </Text>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td className="w-[25px]">
                                                    <User size={16} />
                                                </td>
                                                <td>
                                                    <Text className="text-sm !break-all font-normal text-gray-500">
                                                        www.researchtop/researcher/{user?.username}
                                                    </Text>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>

                                    <div className={show ? "" : "hidden"}>

                                        {/* Work experience */}
                                        {user.work && user.work.length > 0 ?
                                            <div className="mb-5">
                                                <Text className="text-sm font-medium mb-3">Work experience</Text>

                                                {user.work.map((item, i) =>
                                                    <WorkCard
                                                        key={i}
                                                        data={item}
                                                    />
                                                )}
                                            </div>
                                            : null
                                        }

                                        {/* Education */}
                                        {user.education && user.education.length > 0 ?
                                            <div className="mb-5">
                                                <Text className="text-sm font-medium mb-3">Education</Text>

                                                {user.education.map((item, i) =>
                                                    <EducationCard
                                                        key={i}
                                                        data={item}
                                                    />
                                                )}
                                            </div>
                                            : null
                                        }

                                        {/* Other profiles */}
                                        {user.otherProfiles && user.otherProfiles.length > 0 ?
                                            <div>
                                                <Text className="text-sm font-medium mb-3">Other profiles</Text>

                                                {user.otherProfiles.map((item, i) =>
                                                    <SocialCard
                                                        key={i}
                                                        data={item}
                                                    />
                                                )}
                                            </div>
                                            : null
                                        }
                                    </div>

                                    {/* Show more button */}
                                    <div className="mt-2">
                                        <button
                                            type="button"
                                            className="w-full p-1 text-center border rounded-md text-xs text-gray-400 transition-all hover:text-gray-500"
                                            onClick={() => setShow(!show)}
                                        >
                                            {show ? "Show less" : "Show more"}
                                        </button>
                                    </div>
                                </div>
                            </div>
                            : null
                        }

                        {/* Publications list */}
                        {!isLoading && user ?
                            <div className="grow p-5">
                                <DataTable
                                    data={publications}
                                    columns={columns}
                                    loading={publicationLoading}
                                    totalRows={totalRows}
                                    handlePerRowsChange={handlePerRowsChange}
                                    handlePageChange={handlePageChange}
                                    noDataMessage="Publications not available."
                                />
                            </div>
                            : null
                        }
                    </div>
                </div>

            </div>
            <Footer />
        </div>
    );
};

export async function getServerSideProps(context) {
    const { params } = context
    const userName = params.username
    const response = await ResearcherPublicProfile(userName)
    if (response && response.status === 200) {
        return {
            props: {
                userName: userName,
                user: response?.data?.data
            }
        }
    }

    return {
        props: {
            user: null
        }
    }
}

export default index;